### PR TITLE
Encoding codec used by Python 3 pickle

### PR DESCRIPTION
**Pull request by hasibzunair**
Works for both Python 2 and 3 depending on the version being used.

### CODE REVIEW

**Comment by hasibzunair** [comment]
@tgsmith61591 merge possible?

**Comment by tgsmith61591** [comment]
Why are you accessing the private `_Unpickler` class? Why not just pass `encoding` as a kwarg to [`pickle.load`](https://docs.python.org/3/library/pickle.html#pickle.load)?

**Comment by hasibzunair** [comment]
@tgsmith61591 changed it.

**Review by tgsmith61591 — APPROVED** [review]

**Comment by hasibzunair** [comment]
Thanks!

**Pull request merged**
